<?php

namespace JardinBundle\Repository;

/**
 * contratRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class contratRepository extends \Doctrine\ORM\EntityRepository
{
}
