<?php

namespace JardinBundle\Repository;

/**
 * repasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class repasRepository extends \Doctrine\ORM\EntityRepository
{
}
