<?php

namespace JardinBundle\Repository;

/**
 * repasextraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class repasextraRepository extends \Doctrine\ORM\EntityRepository
{
}
